Makefile and file system change

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,1 +1,26 @@
-#Sample Makefile
+DEPENDENCIES=flet sys abc dataclasses
+all:
+	@which pip > /dev/null || (echo "pip not found, installing...Ho" && sudo apt-get update && sudo apt-get install -y python3-pip)
+	@for dependency in $(DEPENDENCIES); do \
+        if ! python -c "import $$dependency" 2>/dev/null; then \
+            echo "$$dependency not found, installing..."; \
+            pip install $$dependency; \
+        fi; \
+    done
+pack: 
+
+doc:
+
+
+test:
+	python3 -m unittest mathlib_suite 
+
+run:
+	python3 -m Calculator
+
+profile:
+	@python -c 'import sys' || (echo "sys module not found, installing..." && pip install sys)
+
+clean:
+
+.PHONY: clean
